### ISSUE TITLE
generate-json schema.json output.json not working with faker values

### ISSUE THREAD

**Issue by fredyfredburger** [oprogramador/json-schema-faker-cli#48]
I don't know if I'm just doing this wrong, but I can't seem to get faker providers to work.  I've tested this on the web GUI to make sure the schema works as intended, but when running in the CLI it keeps outputting lorem ipsum not what the faker provider should output.

Here is the schema I'm using:

```
{
  "type": "object",
  "properties": {
    "test": {
      "type": "string",
      "faker": {
        "fake": "{{address.country}}"
      }
    }
  },
  "required": [
    "test"
  ]
}
```

**Comment by fredyfredburger** [comment]
If it helps, I'm just putting that JSON schema into a schema.json file, then running:

`generate-json schema.json output.json`

The result outputs the test field in a json object, but just lorem ipsum not a random country.

**Comment by oprogramador** [comment]
Thanks for reporting this. I'm not sure when I find time to fix that or to provide any guidelines.

Could you post some screenshots showing how this tool fails, and how it works in another place?

**Comment by fredyfredburger** [comment]
![Working](https://github.com/oprogramador/json-schema-faker-cli/assets/35434572/56a7fbdc-5912-4531-a62c-ae8069f1b95d)
![notWorking](https://github.com/oprogramador/json-schema-faker-cli/assets/35434572/fe58f249-9428-40e2-bd8f-dba9e9b665be)

**Comment by fredyfredburger** [comment]
I found a work-around.  I can just spin up [json-schema-server](https://github.com/json-schema-faker/json-schema-server) and use it from the cmd line with wget.  All I need is for faker values and pattern properties to both work.  The python port of the JSF library doesn't support pattern properties, and the jsf-cli doesn't support calls to the faker-js library.  The json-schema-server supports both, so this issue can be closed.  Thanks!
